esphome:
  name: bigredbutton
  friendly_name: BigRedButton

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

###################
## Default stuff ##
###################

# Enable logging
logger:

# Enable Home Assistant API
api:
  # encryption:
  #   key: "helloworld"

ota:
  - platform: esphome
    password: ''

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Bigredbutton Fallback Hotspot'
    password: 'hkCx4bjOb0Vk'

captive_portal:

####################
## Specific stuff ##
####################
# two_short:d=4,o=5,b=100:16e6,16e6
# star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p
binary_sensor:
  - platform: gpio
    pin: GPIO1
    name: 'Big Button Press'
    interrupt_type: RISING
    on_press:
      - rtttl.play: 'two_short:d=4,o=5,b=100:16e6,16e6'
    entity_category: diagnostic

output:
  - platform: ledc
    pin: GPIO4
    id: buzzer_output
    frequency: 1000 Hz

rtttl:
  output: buzzer_output
  id: my_rtttl
