substitutions:
  name: bigredbutton
  friendly_name: BigRedButton
  hid_unit_name: SEEED Arduino

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

###################
## Default stuff ##
###################

# Enable logging
# logger:

# Enable Home Assistant API
api:
  # encryption:
  #   key: "helloworld"

ota:
  - platform: esphome
    password: ''

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'Bigredbutton Fallback Hotspot'
    password: 'hkCx4bjOb0Vk'

captive_portal:

####################
## Specific stuff ##
####################
# two_short:d=4,o=5,b=100:16e6,16e6
# star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p
### From https://github.com/jensweimann/esphome_ducky/blob/main/esphome/nodemcu.yaml
logger:
  # move esphome's logger to UART1 since we use UART0 for communcation with the arduino
  hardware_uart: UART1
  # disable hardware logging
  baud_rate: 0
  level: INFO

globals:
  # global variable for the hostmachine power state
  - id: last_host_state
    type: std::string
    restore_value: no
    initial_value: ''

external_components:
  - source: github://eigger/espcomponents@latest # https://github.com/eigger/espcomponents/tree/master/components/uartex
    components:
      - uartex
uartex:
  rx_footer: "\r\n"
### End copy from https://github.com/jensweimann/esphome_ducky/blob/main/esphome/nodemcu.yaml

### Button Sensor and debug sound
binary_sensor:
  - platform: gpio
    name: 'Big Button Press'
    pin:
      number: GPIO1
      mode:
        input: true
        pulldown: true
    on_press:
      - logger.log: Button Pressed
      # - rtttl.play: 'star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p'
      - rtttl.play: 'two_short:d=4,o=5,b=100:16e6,16e6'
      - script.execute:
          id: send_text
          ducky_script: |
            STRING Hello, World!
            DELAY 100
            ENTER
    entity_category: diagnostic

output:
  - platform: ledc
    pin: GPIO4
    frequency: 1000 Hz
    id: buzzer_output

rtttl:
  output: buzzer_output
  id: my_rtttl
### End button sensor and debug sound

script:
  - id: send_text
    parameters:
      ducky_script: string
    then:
      - logger.log:
          level: INFO
          format: 'ducky_request: %s'
          args: ['ducky_script.c_str()']
      - uart.write:
          id: ducky
          # encapsulate message with STX and ETX chars and write to serial port
          data: !lambda |-
            char stx = 0x02;
            char etx = 0x03;
            std::string s = stx + ducky_script + etx;
            return std::vector<unsigned char>(s.begin(),s.end());

### Start uart communication stuff with arduino
uart:
  id: ducky
  tx_pin: GPIO43
  rx_pin: GPIO44
  baud_rate: 115200

text_sensor:
  # feedback from arduino
  - platform: template
    name: ${hid_unit_name}_response
    id: ducky_response
    on_value:
      - logger.log:
          level: INFO
          format: 'ducky_response: %s'
          args: ['x.c_str()']

  # host machine's usb serial input forwarding
  - platform: template
    id: ducky_usb_input
    name: ${hid_unit_name}_usb_input

  # serial port sensor
  - platform: uartex
    id: read_line_sensor
    lambda: |-
      return std::string(reinterpret_cast<const char*>(data), len);
    on_value:
      then:
        - if:
            condition:
              # usb serial input forwarding
              lambda: |-
                return str_startswith(x, "USB_INPUT=");
            then:
              - text_sensor.template.publish:
                  id: ducky_usb_input
                  state: !lambda |-
                    x.erase(0,10);
                    return x.c_str();
            else:
              # responses (ready/busy etc.)
              - if:
                  condition:
                    lambda: |-
                      return (x != id(ducky_response).state);
                  then:
                    - text_sensor.template.publish:
                        id: ducky_response
                        state: !lambda |-
                          return x;
